package cosc202.andie.test.cosc202.andie;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions; //class

import cosc202.andie.GaussianBlur;
import cosc202.andie.MeanFilter;

public class FilterKernelTest {
    @Test
    void initialTest(){
    }


    @Test
    void getDefaultGaussianBlurKernel(){
        // Testing that the default size kernel generated by the 
        // GaussianBlur class is the same as the one in the lab book example
        GaussianBlur testBlur = new GaussianBlur();
        // Gaussian Blur class kernel
        float[] blurArray = testBlur.createKernel();
        // Lab book kernel
        float[] testArray = {0.000f, 0.011f, 0.000f,
        0.011f, 0.957f, 0.011f,
        0.000f, 0.011f, 0.000f};
        Assertions.assertArrayEquals(testArray,blurArray, 0.001f);
    }
    
    @Test
    void getDefaultMeanFilterKernel(){
        // Testing that the default size kernel generated by the 
        // MeanFilter class is the same as it should be for a 3x3 kernel
        MeanFilter testBlur = new MeanFilter();
        // Gaussian Blur class kernel
        float[] blurArray = testBlur.createKernel();
        // Real values for 3x3 kernel
        float[] testArray = {1/9.0f, 1/9.0f, 1/9.0f,
            1/9.0f, 1/9.0f, 1/9.0f,
            1/9.0f, 1/9.0f, 1/9.0f};
        Assertions.assertArrayEquals(testArray,blurArray, 0.001f);
    }
}


